---
- name: Linux Health
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Get IP address
      command: hostname -I
      register: ip

    - name: Display IP
      debug:
        var: ip.stdout